### ISSUE TITLE
Geoserver 2.7.2

### ISSUE THREAD

**Issue by loiggeb** [emplexed/gs-mvt#4]
Hi,

We weren't able to use it with 2.7.2. Is there maybe an already compiled version for 2.7.2.

Br,
Bernd

**Comment by stefan0722** [comment]
Normally it should work. I'll retest it with the new version. Did you also install the google protobuf jar as described in the Readme? Is there any error message when starting up the Geoserver?

**Comment by stefan0722** [comment]
Updated and tested successfully with version 2.7.2, provided also a new jar for download.

**Comment by loiggeb** [comment]
Thank you! Now it works! But I think the main problem was, that there were some right-permission issues on the jar file on our machine
