### ISSUE TITLE
empty geometry crashes entire tile

### ISSUE THREAD

**Issue by stvno** [emplexed/gs-mvt#5]
For certain requests gs-mvt fails because it receives an empty geometry. The tilerequest contains multiple geometries as you can see below: the redish areas are vector-tiled neighborhood-polygons, the white square is a failed tile
![tile-failure](https://cloud.githubusercontent.com/assets/394323/12566347/2e72a096-c387-11e5-994c-8797e41162f5.png)

The Geoserver error as stated in the HTTP 500 error

[tileerror.txt](https://github.com/stefan0722/gs-mvt/files/104063/tileerror.txt)

**Comment by stefan0722** [comment]
The quick fix now sorts out geometries with an empty coordinate array. This might happen, if the clipping of a polygon to a tile removes all points. E.g. if the Tile is completely within a Polygon. I also uploaded a new gs-mvt-2.7.2.jar. Please retest if this issue still occurs and no necessary features are missing.

**Comment by stvno** [comment]
I still get the 'empty geometry' error. I was looking into the community [vectortiles](https://github.com/geoserver/geoserver/tree/master/src/community/vectortiles) plugin  and I noticed they use an external java-vector-tile library which checks for empty geometry and uses a [wkt-hack](https://github.com/ElectronicChartCentre/java-vector-tile/blob/879e5e9ec4978776957a7e5aaff3b1aef4d7e4bd/src/main/java/no/ecc/vectortile/VectorTileEncoder.java#L150) to get around empty polygons, might be of use for you.

**Comment by stefan0722** [comment]
Finally found the issue. It was the DouglasPeuckerAlgorithm from the JTS which broke simplified geometries.
